/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DocType = { 'bonPourAccord' : null } |
  { 'facture' : null } |
  { 'devis' : null };
export interface Document {
  'id' : bigint,
  'status' : Status__1,
  'clientId' : bigint,
  'signerPrincipal' : [] | [Principal],
  'createdAt' : bigint,
  'description' : string,
  'signedAt' : [] | [bigint],
  'signatureHash' : [] | [string],
  'missionId' : bigint,
  'proId' : bigint,
  'amount' : bigint,
  'docType' : DocType,
  'vatRate' : bigint,
}
export type Role = { 'pro' : null } |
  { 'client' : null } |
  { 'admin' : null };
export type Status = { 'verified' : null } |
  { 'active' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'suspended' : null };
export type Status__1 = { 'sent' : null } |
  { 'signed' : null } |
  { 'draft' : null } |
  { 'archived' : null };
export interface User {
  'id' : bigint,
  'status' : Status,
  'principal' : Principal,
  'country' : string,
  'createdAt' : bigint,
  'role' : Role,
  'email' : string,
  'language' : string,
  'lastName' : string,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDocument' : ActorMethod<
    [bigint, DocType, bigint, bigint, bigint, bigint, string],
    bigint
  >,
  'filteredUsersSortedByLastName' : ActorMethod<[Role], Array<User>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocument' : ActorMethod<[bigint], Document>,
  'getMyProfile' : ActorMethod<[], User>,
  'getUserById' : ActorMethod<[bigint], User>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDocumentsByMission' : ActorMethod<[bigint], Array<Document>>,
  'listDocumentsByUser' : ActorMethod<[bigint], Array<Document>>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'register' : ActorMethod<
    [Role, string, string, string, string, string],
    User
  >,
  'signDocument' : ActorMethod<[bigint], undefined>,
  'updateProfile' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];