/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DocType = IDL.Variant({
  'bonPourAccord' : IDL.Null,
  'facture' : IDL.Null,
  'devis' : IDL.Null,
});
export const Role = IDL.Variant({
  'pro' : IDL.Null,
  'client' : IDL.Null,
  'admin' : IDL.Null,
});
export const Status = IDL.Variant({
  'verified' : IDL.Null,
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'suspended' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'principal' : IDL.Principal,
  'country' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
  'email' : IDL.Text,
  'language' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Status__1 = IDL.Variant({
  'sent' : IDL.Null,
  'signed' : IDL.Null,
  'draft' : IDL.Null,
  'archived' : IDL.Null,
});
export const Document = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status__1,
  'clientId' : IDL.Nat,
  'signerPrincipal' : IDL.Opt(IDL.Principal),
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'signedAt' : IDL.Opt(IDL.Int),
  'signatureHash' : IDL.Opt(IDL.Text),
  'missionId' : IDL.Nat,
  'proId' : IDL.Nat,
  'amount' : IDL.Nat,
  'docType' : DocType,
  'vatRate' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDocument' : IDL.Func(
      [IDL.Nat, DocType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'filteredUsersSortedByLastName' : IDL.Func(
      [Role],
      [IDL.Vec(User)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocument' : IDL.Func([IDL.Nat], [Document], ['query']),
  'getMyProfile' : IDL.Func([], [User], ['query']),
  'getUserById' : IDL.Func([IDL.Nat], [User], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDocumentsByMission' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'listDocumentsByUser' : IDL.Func([IDL.Nat], [IDL.Vec(Document)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'register' : IDL.Func(
      [Role, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [User],
      [],
    ),
  'signDocument' : IDL.Func([IDL.Nat], [], []),
  'updateProfile' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DocType = IDL.Variant({
    'bonPourAccord' : IDL.Null,
    'facture' : IDL.Null,
    'devis' : IDL.Null,
  });
  const Role = IDL.Variant({
    'pro' : IDL.Null,
    'client' : IDL.Null,
    'admin' : IDL.Null,
  });
  const Status = IDL.Variant({
    'verified' : IDL.Null,
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'principal' : IDL.Principal,
    'country' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
    'email' : IDL.Text,
    'language' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Status__1 = IDL.Variant({
    'sent' : IDL.Null,
    'signed' : IDL.Null,
    'draft' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Document = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status__1,
    'clientId' : IDL.Nat,
    'signerPrincipal' : IDL.Opt(IDL.Principal),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'signedAt' : IDL.Opt(IDL.Int),
    'signatureHash' : IDL.Opt(IDL.Text),
    'missionId' : IDL.Nat,
    'proId' : IDL.Nat,
    'amount' : IDL.Nat,
    'docType' : DocType,
    'vatRate' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDocument' : IDL.Func(
        [IDL.Nat, DocType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'filteredUsersSortedByLastName' : IDL.Func(
        [Role],
        [IDL.Vec(User)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocument' : IDL.Func([IDL.Nat], [Document], ['query']),
    'getMyProfile' : IDL.Func([], [User], ['query']),
    'getUserById' : IDL.Func([IDL.Nat], [User], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDocumentsByMission' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'listDocumentsByUser' : IDL.Func([IDL.Nat], [IDL.Vec(Document)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'register' : IDL.Func(
        [Role, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [User],
        [],
      ),
    'signDocument' : IDL.Func([IDL.Nat], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };