/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface User {
    id: bigint;
    status: Status;
    principal: Principal;
    country: string;
    createdAt: bigint;
    role: Role;
    email: string;
    language: string;
    lastName: string;
    firstName: string;
}
export interface Document {
    id: bigint;
    status: Status__1;
    clientId: bigint;
    signerPrincipal?: Principal;
    createdAt: bigint;
    description: string;
    signedAt?: bigint;
    signatureHash?: string;
    missionId: bigint;
    proId: bigint;
    amount: bigint;
    docType: DocType;
    vatRate: bigint;
}
export enum DocType {
    bonPourAccord = "bonPourAccord",
    facture = "facture",
    devis = "devis"
}
export enum Role {
    pro = "pro",
    client = "client",
    admin = "admin"
}
export enum Status {
    verified = "verified",
    active = "active",
    pending = "pending",
    rejected = "rejected",
    suspended = "suspended"
}
export enum Status__1 {
    sent = "sent",
    signed = "signed",
    draft = "draft",
    archived = "archived"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDocument(missionId: bigint, docType: DocType, clientId: bigint, proId: bigint, amount: bigint, vatRate: bigint, description: string): Promise<bigint>;
    filteredUsersSortedByLastName(roleFilter: Role): Promise<Array<User>>;
    getCallerUserRole(): Promise<UserRole>;
    getDocument(documentId: bigint): Promise<Document>;
    getMyProfile(): Promise<User>;
    getUserById(userId: bigint): Promise<User>;
    isCallerAdmin(): Promise<boolean>;
    listDocumentsByMission(missionId: bigint): Promise<Array<Document>>;
    listDocumentsByUser(userId: bigint): Promise<Array<Document>>;
    listUsers(): Promise<Array<User>>;
    register(role: Role, email: string, firstName: string, lastName: string, country: string, language: string): Promise<User>;
    signDocument(documentId: bigint): Promise<void>;
    updateProfile(userId: bigint, email: string, firstName: string, lastName: string, country: string, language: string): Promise<void>;
}
import type { DocType as _DocType, Document as _Document, Role as _Role, Status as _Status, Status__1 as _Status__1, User as _User, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDocument(arg0: bigint, arg1: DocType, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocument(arg0, to_candid_DocType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocument(arg0, to_candid_DocType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async filteredUsersSortedByLastName(arg0: Role): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.filteredUsersSortedByLastName(to_candid_Role_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filteredUsersSortedByLastName(to_candid_Role_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocument(arg0: bigint): Promise<Document> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_Document_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_Document_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_User_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_User_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserById(arg0: bigint): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_User_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_User_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listDocumentsByMission(arg0: bigint): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDocumentsByMission(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDocumentsByMission(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDocumentsByUser(arg0: bigint): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDocumentsByUser(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDocumentsByUser(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: Role, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.register(to_candid_Role_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5);
                return from_candid_User_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(to_candid_Role_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5);
            return from_candid_User_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async signDocument(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.signDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signDocument(arg0);
            return result;
        }
    }
    async updateProfile(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_DocType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocType): DocType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Document_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Document {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Status__1_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status__1): Status__1 {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_User_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status__1;
    clientId: bigint;
    signerPrincipal: [] | [Principal];
    createdAt: bigint;
    description: string;
    signedAt: [] | [bigint];
    signatureHash: [] | [string];
    missionId: bigint;
    proId: bigint;
    amount: bigint;
    docType: _DocType;
    vatRate: bigint;
}): {
    id: bigint;
    status: Status__1;
    clientId: bigint;
    signerPrincipal?: Principal;
    createdAt: bigint;
    description: string;
    signedAt?: bigint;
    signatureHash?: string;
    missionId: bigint;
    proId: bigint;
    amount: bigint;
    docType: DocType;
    vatRate: bigint;
} {
    return {
        id: value.id,
        status: from_candid_Status__1_n18(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        signerPrincipal: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.signerPrincipal)),
        createdAt: value.createdAt,
        description: value.description,
        signedAt: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.signedAt)),
        signatureHash: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.signatureHash)),
        missionId: value.missionId,
        proId: value.proId,
        amount: value.amount,
        docType: from_candid_DocType_n23(_uploadFile, _downloadFile, value.docType),
        vatRate: value.vatRate
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    principal: Principal;
    country: string;
    createdAt: bigint;
    role: _Role;
    email: string;
    language: string;
    lastName: string;
    firstName: string;
}): {
    id: bigint;
    status: Status;
    principal: Principal;
    country: string;
    createdAt: bigint;
    role: Role;
    email: string;
    language: string;
    lastName: string;
    firstName: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n10(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        country: value.country,
        createdAt: value.createdAt,
        role: from_candid_Role_n12(_uploadFile, _downloadFile, value.role),
        email: value.email,
        language: value.language,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    active: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    suspended: null;
}): Status {
    return "verified" in value ? Status.verified : "active" in value ? Status.active : "pending" in value ? Status.pending : "rejected" in value ? Status.rejected : "suspended" in value ? Status.suspended : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    client: null;
} | {
    admin: null;
}): Role {
    return "pro" in value ? Role.pro : "client" in value ? Role.client : "admin" in value ? Role.admin : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sent: null;
} | {
    signed: null;
} | {
    draft: null;
} | {
    archived: null;
}): Status__1 {
    return "sent" in value ? Status__1.sent : "signed" in value ? Status__1.signed : "draft" in value ? Status__1.draft : "archived" in value ? Status__1.archived : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bonPourAccord: null;
} | {
    facture: null;
} | {
    devis: null;
}): DocType {
    return "bonPourAccord" in value ? DocType.bonPourAccord : "facture" in value ? DocType.facture : "devis" in value ? DocType.devis : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Array<Document> {
    return value.map((x)=>from_candid_Document_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n8(_uploadFile, _downloadFile, x));
}
function to_candid_DocType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocType): _DocType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocType): {
    bonPourAccord: null;
} | {
    facture: null;
} | {
    devis: null;
} {
    return value == DocType.bonPourAccord ? {
        bonPourAccord: null
    } : value == DocType.facture ? {
        facture: null
    } : value == DocType.devis ? {
        devis: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    pro: null;
} | {
    client: null;
} | {
    admin: null;
} {
    return value == Role.pro ? {
        pro: null
    } : value == Role.client ? {
        client: null
    } : value == Role.admin ? {
        admin: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
